[project]
name = 'bug-clarinet-costs'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.tester]
path = 'contracts/tester.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
